### PR TITLE
Fixed #357 Add test to confirm that Android 2M limit is resolved

### LINKED ISSUE #357: Replace default Android storage engine to support JSON docs > 2Meg
The default android storage engine, that wraps SQLite has a CursorWindow class that limits content of a single row to 2MBytes. This results in errors for large JSON documents.

CursorWindow is specific to the Android storage engine framework, the issue is not seen on iOS or Portable Java.

Need a strategy for replacing the default Android storage engine to fix this.

1) Is it possible to access the embedded android SQLite directly via our own storage engine, can we cope with different SQLite versions on different devices?

2) Provide an optional external SQLite native library (i.e. from Portable Java) with our own storage engine. Can we cover all Android target architectures (ARM/Intel?) using a custom build.

### PR DESCRIPTION
**Pull request by pasin**
- Currently we are using our own ported Android SQLiteDatabase which doesn't use Android's WindowsCursor so we don't have the same 2M blob limitation.

- Added DatabaseTest.testAndroid2MLimit to confirm that.

#357

### CODE REVIEW

**Comment by jayminraval** [comment]
@hideki I am currently having the same issue of WindowsCursor when getting the Map<String, Object> properties from a large document. Do you have any pointers on how did you "port Android SQLiteDatabase which doesn't use Android's WindowsCursor" ?

**Comment by hideki** [comment]
Hi @jayminraval, 
Please use v1.2.0 that does not use Android default SQLDatabase.

**Comment by jayminraval** [comment]
@hideki Ok, thanks for reply. Will try and let you know.

**Comment by jayminraval** [comment]
@hideki I tried and it works great! Thanks. Another question - I was previously (couchbase 1.1.0) pulling the .cblite file for viewing data and debugging. Now (couchbase 1.2.0) I see that it has been replaced with db.sqlite3. I am using a Sqlite viewer app on my mac, but can only see the docids, and not the json data. I need to see the json data. Am I missing something? Also, when I used another viewer app, it said that the database was encrypted and required me to enter the encryption key.

**Comment by hideki** [comment]
Hi @jayminraval ,

Please use https://github.com/couchbaselabs/CouchbaseLiteViewer.

> Also, when I used another viewer app, it said that the database was encrypted and required me to enter the encryption key.

Are you using encryption?

**Comment by jayminraval** [comment]
@hideki I tried using CouchbaseLiteViewer, but when I select File > Open..., then the db.sqlite3 file is not selectable. 
No, I am not using encryption.

**Comment by jayminraval** [comment]
@hideki I see that couchbase creates the following files - 
/data/user/0/com.mioglobal.android.miogo.pai/files/cb_mio.cblite2/db.sqlite3
/data/user/0/com.mioglobal.android.miogo.pai/files/cb_mio.cblite2/db.sqlite3-wal
/data/user/0/com.mioglobal.android.miogo.pai/files/cb_mio.cblite2/db.sqlite3-shm

So, all the json data should be in the sqlite3 file, right? The other wal and shm files are just temp files. 
CouchbaseLiteViewer cannot open db.sqlite3. So, I tried using SQLiteManager, but that shows the encryption error.

**Comment by hideki** [comment]
Can you open entire directory (cb_xx.cblite2) with Viewer? not only sqlite3 file.

**Comment by jayminraval** [comment]
@hideki Havent tried that. Will do and let you know. I could open the db.sqlite3 in SQLItePro, and see that the structure of the data storage has changed quite a bit. Couldn't find the actual json string data location, although the "revs" table had the "json" column which had meta data values such as "text/plain; 300kb". 
Would it be possible to point me in the direction where the actual json data is stored?

**Comment by hideki** [comment]
`json` filed should be in `revs` table.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L89
CBL uses custom collator for json field for sorting. It might prevent to show the `json` field with the tool you are using.
Using CBL Viewer could be best choice.

**Comment by jayminraval** [comment]
@hideki I copied over all the files (db.sqlite3, db.sqlite3-wal, db.sqlite3-shm, attachments folder), and tried to File > Open from CouchbaseViewer, but it still has the issue, where I can select the folder from the explorer, I then click Open, which simply opens the folder in the explorer, and then all the 3 files listed above will be greyed out (not selectable), I tried creating a new db using CouchbaseViewer, to see what structure does it expect, by File > New, but nothing happens, as in no GUI opens for me to create new db / documents.

**Comment by hideki** [comment]
Hi @jayminraval,
"File" -> "Open". From Dialog, please select <databasename>.cblite2.

**Comment by hideki** [comment]
Hi @jayminraval,
I just tried `sqlite3` command. I can see `json` field.
you can simply call following: `select json from revs;`

**Comment by vasticles** [comment]
Hi @hideki 
I'm running into the same issues as @jayminraval. Can't open the .cblite2 directory using the latest version of the Viewer. Any suggestions?

**Comment by hideki** [comment]
@vasticles Could you please re-clone from github (https://github.com/couchbaselabs/CouchbaseLiteViewer), and rebuild it?

**Comment by vasticles** [comment]
@hideki 
I followed the instructions, but couldn't manage to build it. 
https://gyazo.com/ac829389e7672970684946fac9a3a338
PS. I'm an Android dev, so Xcode is unfamiliar territory for me :X

**Comment by hideki** [comment]
Hi @vasticles 
Please download the compiled one from following link. It could work.
https://github.com/couchbaselabs/CouchbaseLiteViewer/releases/tag/untagged-fa4bdda111f722e8526c

**Comment by vasticles** [comment]
@hideki 
I'm getting a 404 from that link

**Comment by hideki** [comment]
@vasticles Sorry, it is Draft release. It seems the link is only accessible from member of Couchbase. What is best way to share the binary?

**Comment by vasticles** [comment]
@hideki 
Dropbox, or Google Drive, or whatever works.
Thanks!

**Comment by vasticles** [comment]
@hideki 
Sorry, hope I didn't come off rude.
I usually use Google Drive for sharing files, but whatever works best for you. Not sure what else to suggest.

**Comment by hideki** [comment]
@vasticles , can you create folder on Google Drive, and share the folder with me, "hideki at couchbase dot com"?

**Comment by vasticles** [comment]
@hideki 
Shared :)

**Comment by hideki** [comment]
@vasticles I posted app to folder. please confirm.

**Comment by vasticles** [comment]
@hideki 
Nothing yet. https://gyazo.com/15a455e2e02db34699951e709eaf6dd5

**Comment by hideki** [comment]
It seems my couchbase account share file with couchbase people.

Please invite "hideki dot itakura at gmail dot com"?

Sorry!

**Comment by hideki** [comment]
@vasticles, I shared folder from my personal account. Please confirm.

**Comment by vasticles** [comment]
@hideki 
That worked. Finally managed to open .cblite2 directory.
Thanks so much!

**Comment by hideki** [comment]
glad to hear!

**Pull request merged**
